### ISSUE TITLE
GUI Implementation: Main Menu

### ISSUE THREAD

**Issue by aburkhalter512** [aburkhalter512/EpochEscape#4]
## Overview

This issue covers the progress of the Main Menu GUI implementation
## Work Items
- [X] GUI Object Component
- [ ] Ease of Use Classes
  - [x] Button
  - [ ] Dialog
  - [x] Scroll Bar
- [ ] Screens
  - [ ] Main
    - [ ] Level Selection
      - [ ] Pre-built levels
      - [ ] User selected levels
    - [x] Editor
    - [ ] Options
    - [ ] Credits
