### ISSUE TITLE
GUI Design: Main Menu

### ISSUE THREAD

**Issue by aburkhalter512** [aburkhalter512/EpochEscape#6]
## Overview

This issue covers the progress of the Main Menu Design
## Work Items
- [x] Paper Prototype (image below)
- [x] Create Graphics (image below)
- [x] Create Computer Graphic Mockup (image below)

**Comment by aburkhalter512** [comment]
## Paper Prototype

![scan009](https://cloud.githubusercontent.com/assets/4406460/9031104/126c1ed6-3962-11e5-8d83-697485572192.jpg)
![scan011](https://cloud.githubusercontent.com/assets/4406460/9031105/1364bf14-3962-11e5-8a1d-00f07bea9526.jpg)
![scan010](https://cloud.githubusercontent.com/assets/4406460/9031106/14cb0a0c-3962-11e5-9f0c-70dda9ef2d75.jpg)

**Comment by aburkhalter512** [comment]
## Main Menu Graphics

### Titles

![epochescape](https://cloud.githubusercontent.com/assets/4406460/10341262/e533bab0-6cc8-11e5-8b70-42b2a29ff436.png)
![epochlevels](https://cloud.githubusercontent.com/assets/4406460/10341264/e84014ec-6cc8-11e5-8032-ba35525f0178.png)
![epochoptions](https://cloud.githubusercontent.com/assets/4406460/10341265/ea3f9a1a-6cc8-11e5-9212-7ea44bbfc6e3.png)

### Buttons

![levelsbutton](https://cloud.githubusercontent.com/assets/4406460/10341307/0bc441a4-6cc9-11e5-80fb-5d60bc38f4ce.png)
![levelsbuttonhover](https://cloud.githubusercontent.com/assets/4406460/10341359/3abd0996-6cc9-11e5-9cd0-c0cd22a0d7be.png)
![editorbutton](https://cloud.githubusercontent.com/assets/4406460/10341312/0eb5dc56-6cc9-11e5-9641-ae8b718e4089.png)
![editorbuttonhover](https://cloud.githubusercontent.com/assets/4406460/10341363/41ac5842-6cc9-11e5-9d62-1b46db7247d5.png)
![optionsbutton](https://cloud.githubusercontent.com/assets/4406460/10341320/12f4025c-6cc9-11e5-80b8-4175dcce8032.png)
![optionsbuttonhover](https://cloud.githubusercontent.com/assets/4406460/10341373/48ab761e-6cc9-11e5-9418-f25fe5fb3d88.png)
![exitbutton](https://cloud.githubusercontent.com/assets/4406460/10341323/15318350-6cc9-11e5-8360-ff085b1e1203.png)
![exitbuttonhover](https://cloud.githubusercontent.com/assets/4406460/10341385/4e7c7174-6cc9-11e5-8f67-22ab394c9e85.png)
![exit](https://cloud.githubusercontent.com/assets/4406460/10341397/584c5066-6cc9-11e5-9a4b-97c6cd1c8b7a.png)
![exithover](https://cloud.githubusercontent.com/assets/4406460/10341399/5a3c0eb6-6cc9-11e5-9d7f-75678e5e8a50.png)
![leftarrow](https://cloud.githubusercontent.com/assets/4406460/10341400/5d7c2ebc-6cc9-11e5-981c-8364daac5661.png)
![leftarrowhover](https://cloud.githubusercontent.com/assets/4406460/10341404/6289df80-6cc9-11e5-9207-86047a398dca.png)

#### Scroll Bar

![slider](https://cloud.githubusercontent.com/assets/4406460/10381866/2c8f862c-6dd3-11e5-97a1-a52827bcc15f.png)
![sliderhover](https://cloud.githubusercontent.com/assets/4406460/10381865/2c8e3240-6dd3-11e5-8d99-511407eb3e41.png)
![horiztrack](https://cloud.githubusercontent.com/assets/4406460/10381942/bca680bc-6dd3-11e5-9ffe-803bbe6de8a4.png)
![verttrack](https://cloud.githubusercontent.com/assets/4406460/10381943/bca8127e-6dd3-11e5-88d9-ea71e4386b7b.png)
![downarrow](https://cloud.githubusercontent.com/assets/4406460/10382061/dcfa7dae-6dd4-11e5-9fd2-7368f0a4f2b6.png)
![downarrowhover](https://cloud.githubusercontent.com/assets/4406460/10382062/dcfa9226-6dd4-11e5-85d0-58fd7b26e6df.png)
![leftarrow](https://cloud.githubusercontent.com/assets/4406460/10382059/dcfa0d74-6dd4-11e5-932e-e5742e69f3a0.png)
![leftarrowhover](https://cloud.githubusercontent.com/assets/4406460/10382058/dcf93f98-6dd4-11e5-959f-3f4cd604b14f.png)
![rightarrow](https://cloud.githubusercontent.com/assets/4406460/10382060/dcfa5acc-6dd4-11e5-81ab-269527b14a3e.png)
![rightarrowhover](https://cloud.githubusercontent.com/assets/4406460/10382057/dcf93f84-6dd4-11e5-8928-f94ed8a83b3a.png)
![uparrow](https://cloud.githubusercontent.com/assets/4406460/10382063/dd0dc080-6dd4-11e5-9b74-31f26423c906.png)
![uparrowhover](https://cloud.githubusercontent.com/assets/4406460/10382064/dd0f150c-6dd4-11e5-9573-8b4f28c015ab.png)

**Comment by aburkhalter512** [comment]
## Mockups

#### Main Menu

![main menu](https://cloud.githubusercontent.com/assets/4406460/10382506/82ac3db0-6dd9-11e5-8de6-e37210193019.png)

#### Levels Menu

![levelsmenu](https://cloud.githubusercontent.com/assets/4406460/10446490/28c97cc0-7132-11e5-90c0-94efb092c302.png)

#### Options Menu

![optionsmenu](https://cloud.githubusercontent.com/assets/4406460/10446493/2e84c17e-7132-11e5-9a9b-cd41f8029b3a.png)

**Comment by aburkhalter512** [comment]
All major graphics for the main menu are complete.
