### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by aburkhalter512** [aburkhalter512/EpochEscape#7]
## Overview

This issue covers the progress of User Testings
## Work Items
- [ ] Generate List of Potential Participants
- [ ] Contact Potential Participants
- [ ] Schedule Testing sessions
- [ ] Create Tester Instructions
  - [ ] Add basic questions (scale)
  - [ ] Add open ended questions (user answer)
  - [ ] Add audio recording instructions
  - [ ] Add pictures/screenshot instructions
- [ ] User Testing Round 1
  - [ ] Results Gathered
  - [ ] Results Processed
  - [ ] Priority List Created (by weight)
- [ ] User Testing Round 2
  - [ ] Results Gathered
  - [ ] Results Processed
  - [ ] Priority List Created (by weight)
